# -*- coding: utf-8 -*-
"""cobastopwatch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e1D5d4l2MS0tL51FOoUDfis0TkR4miEh
"""

import streamlit as st
import time
import threading


def main():
    st.title("Stopwatch App")

    # Parameter
    Jarak = st.number_input("Masukkan Jarak Front ke Disposal (KM): ")
    Speed = 25
    DisposalTime = 60
    WaitingTime = 120

    # Formula
    Waktu1 = (Jarak + Jarak) / Speed
    Menit = Waktu1 * 60
    Detik = Menit * 60

    # Total Cycle HD dengan Parameter Speed 25 dan Jarak yang terinput
    # Dalam Total Cycle Time HD juga sudah diberikan waktu Disposal 1 Menit dan Waiting Time 2 Menit, Sehingga:
    WaktuTotal = Detik + DisposalTime + WaitingTime
    st.write(f"Waktu Cycle Time Anda {WaktuTotal / 60} Menit")

    Waktu = (WaktuTotal)

    # Global variables
    stop_timer = False

    def stopwatch(duration):
        start_time = time.time()
        end_time = start_time + duration

        st.write("Siap! Waktu Dimulai!")

        def print_elapsed_time():
            while not stop_timer and time.time() < end_time:
                elapsed_time = time.time() - start_time
                hours = int(elapsed_time / 3600)
                minutes = int((elapsed_time % 3600) / 60)
                seconds = int(elapsed_time % 60)
                st.write(f"Waktu Berjalan: {hours:02d}:{minutes:02d}:{seconds:02d}")
                time.sleep(1)

            if stop_timer:
                st.write("Waktu Dihentikan!")
            else:
                st.write("Waktu Anda Habis!")

        timer_thread = threading.Thread(target=print_elapsed_time)
        timer_thread.start()

        # Menghentikan Program ketik s
        stop_input = st.text_input("Tekan 'S' untuk menghentikan waktu:")
        if stop_input.lower() == 's':
            nonlocal stop_timer
            stop_timer = True

        timer_thread.join()

    stopwatch(Waktu)

if __name__ == '__main__':
    main()