# -*- coding: utf-8 -*-
"""CobaHitungMundur

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1v2EnGLgyWXU6iHSkskeqC8GllVhTZnM3
"""

import streamlit as st
import time

st.set_page_config()
st.title("Operasi Jam Pama Watch")

# Memasukkan panjang jalur dalam kilometer
panjang = st.number_input("Panjang Jalur (km): ")
kecepatan = 24

# Menghitung waktu operasi ideal
waktu_ideal = (panjang/kecepatan) * 60

st.text("Waktu Ideal Operasi tiap Siklus adalah {} detik".format(waktu_ideal))

def hitung_waktu():
    tampil_waktu = st.empty()
    N = 24*60*60
    total_detik = 0
    a = 2

    for detik in range(0, N, 1):
        menit, detik = divmod(detik, 60)
        tampil_waktu.metric("Waktu Anda", f"{menit:02d}:{detik:02d}")
        time.sleep(1)
        total_detik += detik
        if a == 1:
            break
    return total_detik

tbl_mulai = st.button("Mulai")

if tbl_mulai:
    total_detik = hitung_waktu()