# -*- coding: utf-8 -*-
"""Stopwatch.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g-O7EqRrGGrsCR_OSiINIfYa7pF84Z8o
"""

import streamlit as st
import time
import threading
import sys
from datetime import datetime, timedelta

def countdown(t):
    start_time = datetime.now()
    end_time = start_time + timedelta(seconds=t)

    while datetime.now() < end_time and not stop_event.is_set():
        elapsed_time = datetime.now() - start_time
        remaining_time = t - elapsed_time.total_seconds()
        timer = f"{int(remaining_time)} Detik"
        st.text(timer)
        time.sleep(0.1)

    if not stop_event.is_set():
        st.text(f"Waktu habis! {t} Detik")

def stop_countdown():
    stop_event.set()

# Masukkan waktu dalam detik
waktu_total = 6

# Membuat objek threading.Event untuk menghentikan countdown
stop_event = threading.Event()

# Membuat thread untuk menjalankan countdown
countdown_thread = threading.Thread(target=countdown, args=(waktu_total,))
countdown_thread.start()

# Menampilkan tombol 'Stop' untuk menghentikan countdown
if st.button('Stop'):
    stop_countdown()
    countdown_thread.join()

# Menampilkan waktu mundur terakhir sebelum dihentikan
elapsed_time = datetime.now() - datetime.now()
timer = str(elapsed_time).split('.')[0]
st.text("Waktu mundur terakhir: " + timer)